package org.example.year2024.day21;

public enum DirectionOrder {
    UP_RIGHT_LEFT_DOWN,
    UP_RIGHT_DOWN_LEFT,
    UP_LEFT_RIGHT_DOWN,
    UP_LEFT_DOWN_RIGHT,
    RIGHT_UP_DOWN_LEFT,
    RIGHT_UP_LEFT_DOWN,
    RIGHT_DOWN_UP_LEFT,
    RIGHT_DOWN_LEFT_UP,
    DOWN_LEFT_UP_RIGHT,
    DOWN_LEFT_RIGHT_UP,
    DOWN_RIGHT_UP_LEFT,
    DOWN_RIGHT_LEFT_UP,
    LEFT_UP_RIGHT_DOWN,
    LEFT_UP_DOWN_RIGHT,
    LEFT_DOWN_UP_RIGHT,
    LEFT_DOWN_RIGHT_UP;
}
